routes/web.php
    Route::resource('ambulance-bookings',PatientAmbulanceBookingController::class);
//    Route::get('book-ambulance/{id}',[PatientAmbulanceBookingController::class,'create']);
//    Route::get('book-ambulance/{id}/edit',[PatientAmbulanceBookingController::class,'edit']);
    Route::get('my-wallet',[PatientWalletController::class,'index'])->name('patient.wallet');
    Route::get('wallet-transaction-detail/{id}',[PatientWalletController::class,'show'])->name('patient.wallet-detail');
    Route::post('recharge-wallet',[PatientWalletController::class,'addMoney'])->name('patient.wallet-recharge');
});

/*
 * End Of Patient Module
 */

/*
 *Provider module
 */

Route::group(['middleware'=>'auth','provider'],function(){
    Route::get('dashboard',[ProviderDashboardController::class,'index'])->name('provider.dashboard');
    Route::get('update-profile',[ProviderDashboardController::class,'updateProfile']);
    Route::post('updatePersonalInfo',[ProviderDashboardController::class,'personalInfoUpdate']);
//Route::post('updateServicesInfo','Web\DashboardController::class,'serviceInfoUpdate')->middleware('auth');
    Route::post('updateDocuments',[ProviderDashboardController::class,'documentUpdate']);
    Route::resource('services',ServiceController::class);
    Route::post('services-images',[ServiceController::class,'saveServicesImages']);
    Route::get('enquiries',[CommonProviderController::class,'myEnquiries']);
    Route::get('reviews-ratings',[CommonProviderController::class,'myReviewRating']);
    Route::get('reply-enquiry/{id}',[CommonProviderController::class,'loadReplyView']);
    Route::post('save-reply',[CommonProviderController::class,'savePatientEnquiryReply']);
    Route::get('event/manage',[EventController::class,'index']);
    Route::get('event/update-event/{id}',[EventController::class,'editEvent']);
    Route::post('event/update',[EventController::class,'update']);
    Route::get('event/add',[EventController::class,'createEvent']);
    Route::post('event/add',[EventController::class,'store']);
    Route::get('event',[EventController::class,'calender']);
    Route::delete('event/remove',[EventController::class,'destroy']);
    Route::get('schedule-by-day/{id}',[EventController::class,'getScheduleByDate']);
    Route::post('change-live-status',[ProviderDashboardController::class,'changeLiveStatus']);
    Route::post('consultation-response',[LiveConsultationController::class,'saveResponse']);
    Route::get('medical-data/{id}',[LiveConsultationController::class,'getAllMedicalDataList']);
    Route::get('consultation-data/{id}',[LiveConsultationController::class,'getAllLiveConsultationDataList']);
    Route::get('appointment-data/{id}',[LiveConsultationController::class,'getAllAppointmentDataList']);
    Route::get('view-medical-data/{id}',[LiveConsultationController::class,'getMedicalDataDetail']);
    Route::get('view-live-consultation-data/{id}',[LiveConsultationController::class,'getLiveConsultationDataDetail']);
    Route::get('view-appointment-booking-data/{id}',[LiveConsultationController::class,'getAppointmentDataDetail']);
    Route::post('checkPaymentStatus',[LiveConsultationController::class,'isPaid']);
    Route::post('initiate-consultation-call',[LiveConsultationController::class,'initiateCall']);
    Route::post('hang-call',[LiveConsultationController::class,'removeCall']);
    Route::resource('live-consultation',LiveConsultationController::class);
    Route::post('changePassword',[CommonProviderController::class,'changeProviderPassword']);
    Route::post('submitRequestResponse',[AmbulanceProviderController::class,'updateRequestResponse']);
    Route::resource('ambulance-bookings',AmbulanceProviderController::class);
    Route::get('booking/get-bookings',[BookingScheduleController::class,'getMyBooking']);
    Route::get('booking/edit/{id}',[BookingScheduleController::class,'edit']);
    Route::post('booking/update',[BookingScheduleController::class,'update']);
    Route::delete('booking/remove',[BookingScheduleController::class,'destroy']);
    Route::get('booking/edit-appointment/{id}',[BookingScheduleController::class,'editAppointmentDetail']);
    Route::post('appointment-update',[BookingScheduleController::class,'updateAppointment']);
    Route::post('update-appointment-time',[BookingScheduleController::class,'updateAppointmentTime']);
});

/*
 * End Of Provider Module
 */
Route::group(['prefix' => 'omed','middleware'=>'admin'],function(){
    Route::get('dashboard',[DashboardController::class,'index']);
    Route::post('logout',[LoginController::class,'logout']);
    Route::resource('category',CategoryController::class);
    Route::resource('user-management',UserManagementController::class);
    Route::get('update-provider-profile/{id}',[UserManagementController::class,'loadUpdateProfile']);
    Route::get('patient/online-bookings/{id}',[PatientManagementController::class,'getAllOnlineBookings',]);
    Route::get('patient/omed-coins/{id}',[PatientOmedCoinController::class,'index',]);
    Route::get('patient-management/show-consultation-booking/{id}',[PatientManagementController::class,'getOnlineBookingDetails',]);
    Route::post('patient-management/remove-consultation-booking',[PatientManagementController::class,'removeOnlineBooking',]);
    Route::post('patient-management/remove-directory',[PatientManagementController::class,'removeMedicalDirectory']);
    Route::resource('gallery',GalleryController::class);
//    Route::resource('pages',PageController::class);
    Route::get('show-medical-data/{id}',[PatientManagementController::class,'browsMedicalDirectory']);
    Route::resource('enquiry-management',EnquiryController::class);
    Route::post('addNewCategory',[UserManagementController::class,'storeNewCategory']);
    Route::post('removeFromService',[UserManagementController::class,'serviceRemove']);
    Route::post('manageContactButton',[UserManagementController::class,'manageButtonAccess']);
    Route::post('update-services-images',[UserManagementController::class,'updateServicesImages']);
    Route::resource('media', MediaController::class)->middleware('admin');
    Route::resource('content', ContentController::class)->middleware('admin');
    Route::post('updateProviderServiceInfo',[UserManagementController::class,'updateServiceInfo']);
    Route::post('updateProviderDocuments',[UserManagementController::class,'updateDocument']);
    Route::post('updateProviderServicesInfo',[UserManagementController::class,'updateServiceInfo']);
    Route::post('updateProviderPersonalInfo',[UserManagementController::class,'updatePersonalInfo']);
    Route::get('service-provider/ratings/{id}',[UserManagementController::class,'getAllReviews']);
    Route::get('service-provider/patient-enquiries/{id}',[UserManagementController::class,'getAllEnquiries']);
    Route::get('service-provider/offline-bookings/{id}',[UserManagementController::class,'getAllOfflineBookings',]);
    Route::get('service-provider/online-bookings/{id}',[UserManagementController::class,'getAllOnlineBookings',]);
    Route::get('user-management/show-booking/{id}',[UserManagementController::class,'getBookingDetails',]);
    Route::post('user-management/remove-booking',[UserManagementController::class,'removeOfflineBooking',]);
    Route::get('user-management/show-consultation-booking/{id}',[UserManagementController::class,'getOnlineBookingDetails',]);
    Route::post('user-management/remove-consultation-booking',[UserManagementController::class,'removeOnlineBooking',]);
    Route::post('user-management/remove-rating',[UserManagementController::class,'removeReviewRatings']);
    Route::post('user-management/remove-enquiry',[UserManagementController::class,'removeEnquiry']);
    Route::get('user-management/show-enquiry/{id}',[UserManagementController::class,'getEnquiryDetails']);
    Route::post('user-management/admin-reply',[UserManagementController::class,'saveAdminReply']);
    Route::get('view-prescription/{id}',[OnlineBookingController::class,'getPrescription']);
    Route::get('patient/offline-bookings/{id}',[PatientManagementController::class,'getAllOfflineBookings',]);
    Route::get('patient/show-booking/{id}',[PatientManagementController::class,'getBookingDetails',]);
    Route::post('patient/remove-booking',[PatientManagementController::class,'removeOfflineBooking',]);
    Route::resource('patient-management',PatientManagementController::class);
    Route::post('markTopCategory',[UserManagementController::class,'markAsTop']);
//    Route::resource('state',StateController::class);
    Route::resource('district',DistrictController::class);
    Route::resource('area',AreaController::class);
    Route::resource('offline-booking-management',OfflineBookingController::class);
    Route::resource('online-booking-management',OnlineBookingController::class);
    Route::resource('ambulance-booking-management',AmbulanceBookingController::class);
    Route::resource('manage-settings',SettingController::class);
    Route::get('patient/omed-coins/{id}',[PatientOmedCoinController::class,'index'])->name('omed-coins.index');
    Route::get('patient/omed-coins/{id}/show',[PatientOmedCoinController::class,'show'])->name('omed-coins.show');
    Route::post('patient/omed-coins/store',[PatientOmedCoinController::class,'store'])->name('omed-coins.store');
    Route::delete('patient/omed-coins/{id}',[PatientOmedCoinController::class,'destroy'])->name('omed-coins.destroy');
});

Route::get('ajax/change-flag',[AjaxController::class,'changeFlag'])->middleware('admin');
Route::get('ajax/generate-puid',[AjaxController::class,'generatePUID'])->middleware('admin');
Route::post('change-flag',[AjaxController::class,'changeFlag']);
Route::get('ajax/state',[AjaxController::class,'getCity']);
Route::get('ajax/subcategory/{role}',[AjaxController::class,'getSubCategory']);
Route::get('ajax/city',[AjaxController::class,'getArea']);
Route::get('ajax/saveLocation',[WebAjaxController::class,'savePatientLocation']);

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Location extends Model
{
    use HasFactory;
    protected $guarded = [];
}

resources/views/admin/location/area.blade.php
@extends('layouts.master')
@section('breadcumb')
    <!-- Breadcome start-->
    <div class="breadcome-area mg-b-30 small-dn">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcome-list map-mg-t-40-gl shadow-reset">
                        <ul class="breadcome-menu">
                            <li><a href="{{url('omed/dashbard')}}">Dashboard</a> <span class="bread-slash">/</span>
                            </li>
                            <li><a href="#">Area</a> <span class="bread-slash"></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <!-- Static Table Start -->
    <div class="data-table-area mg-b-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12"><div style="margin-bottom: 10px; padding-bottom:10px;">
                        <button title="Add New" onclick="window.location.href ='{{url('omed/area/create')}}'" class="btn btn-primary add-button" type="button" style="float:right;">
                            <i class="fa fa-plus"></i>
                        </button> <br>
                    </div>


                    <div class="sparkline12-list shadow-reset mg-b-15">
                        <div class="sparkline12-hd">
                            <div class="main-sparkline12-hd">
                                <h1>Search Area<span class="table-project-n"> List</span> </h1>
                                <div class="sparkline12-outline-icon">
                                    <span class="sparkline12-collapse-link"><i class="fa fa-chevron-up"></i></span>
                                    {{-- <span><i class="fa fa-wrench"></i></span> --}}
                                    {{-- <span class="sparkline13-collapse-close"><i class="fa fa-times"></i></span> --}}
                                </div>
                            </div>
                        </div>
                        <div class="sparkline12-graph">
                            <form method="post" action="{{url('omed/get-area')}}">
                                @csrf
                                <div class="form-group-inner">
                                    <div class="row">
                                        <div class="col-lg-3">
                                            <label class="login2 pull-right pull-right-pro">State</label>
                                        </div>
                                        <div class="col-lg-4">
                                            <select class="select2_demo_2 form-control state-select "   name="state" required style="width:100%;" >
                                                <option selected disabled>State</option>
                                                @foreach($states as $s)
                                                    <option value="{{$s->name}}" >{{ucwords($s->name)}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group-inner">
                                    <div class="row">
                                        <div class="col-lg-3">
                                            <label class="login2 pull-right pull-right-pro">City</label>
                                        </div>
                                        <div class="col-lg-4">
                                            <select class="select2_demo_2 form-control city-select "   name="city" required style="width:100%;"  >
                                                <option selected disabled>City</option>

                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group-inner">
                                    <div class="login-btn-inner">
                                        <div class="row">
                                            <div class="col-lg-3"></div>
                                            <div class="col-lg-6">
                                                <div class="login-horizental cancel-wp pull-left">
                                                    <button class="btn btn-white" type="button" onclick="window.history.back();">Cancel</button>
                                                    <button class="btn btn-sm btn-primary login-submit-cs" type="submit">Show</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>



                    <div class="sparkline13-list shadow-reset">
                        <div class="sparkline13-hd">
                            <div class="main-sparkline13-hd">
                                <h1>Area<span class="table-project-n"> List</span> </h1>
                                <div class="sparkline13-outline-icon">
                                    <span class="sparkline13-collapse-link"><i class="fa fa-chevron-up"></i></span>
                                    {{-- <span><i class="fa fa-wrench"></i></span> --}}
                                    {{-- <span class="sparkline13-collapse-close"><i class="fa fa-times"></i></span> --}}
                                </div>
                            </div>
                        </div>
                        <div class="sparkline13-graph">
                            <div class="datatable-dashv1-list custom-datatable-overright">
                                <div id="toolbar">
                                    <select class="form-control">
                                        <option value="">Export Basic</option>
                                        <option value="all">Export All</option>
                                        <option value="selected">Export Selected</option>
                                    </select>
                                </div>
                                <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true" data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                    <thead>
                                    <tr>
                                        <th data-field="state" data-checkbox="true"></th>
                                        <th data-field="id">S.No.</th>
                                        <th data-field="area"></th>
                                        <th data-field="district">District</th>
                                        <th data-field="state_name">State</th>
                                        <th data-field="pincode">Pincode</th>
                                        <th data-field="action">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @if(isset($list))
                                    @php $num=1 @endphp
                                    @foreach($list as $data)
                                        <tr>
                                            <td></td>
                                            <td>{{$num}}</td>

                                            <td>{{$data->area}}</td>
    <td>{{$data->city}}</td>
                                            <td>{{$data->state}}</td>
<td>{{$data->pincode}}</td>
                                            <td>
                                                <div class="fr">
                                                    <a href="{{route('area.edit',$data->id)}}" class="btn btn-custon-four btn-primary"><span class="adminpro-icon adminpro-informatio"></span> Edit</a>
                                                    <a href="javascript:void(0)" data-url="{{route('area.destroy',$data->id)}}" data-id="{{$data->id}}" data-toggle="modal" data-target="#WarningModalhdbgcl" class="btn btn-custon-four btn-danger delete_button_action"><span class="adminpro-icon adminpro-danger-error"></span> Delete</a>
                                                </div>
                                            </td>
                                        </tr>
                                        @php $num++ @endphp

                                    @endforeach
                                        @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Static Table End -->
@endsection
@section('additional_script')
    <script>
        $('.state-select').change(function() {
            $.ajax({
                type:"GET",
                url:"{{url('ajax/state')}}?state="+$(this).val(),
                success: function(response) {
                    if (response.success) {
                        $('.city-select').find('option').remove().end().append('<option selected hidden disabled>City</option>');
                        var city = response.city;
                        $.each(city, function(i, d) {
                            $('.city-select').append('<option>' + d.name + '</option>');
                        });
                    }
                },
            });
        });

        // City Change
        $('.city-select').change(function() {
            $.ajax({
                type:"GET",
                url:"{{url('ajax/city')}}?city="+$(this).val()+'&state='+$('.state-select').val(),
                success: function(response) {
                    if (response.success) {
                        $('.area-select').find('option').remove().end().append('<option selected hidden disabled>Area</option>');
                        var area = response.area;
                        $.each(area, function(i, d) {
                            $('.area-select').append('<option>' + d.area + '</option>');
                        });
                    }
                },
            });
        });
    </script>
@endsection

resources/views/admin/location/area_form.blade.php
@extends('layouts.master')
@section('breadcumb')
    <!-- Breadcome start-->
    <div class="breadcome-area mg-b-30 small-dn">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcome-list map-mg-t-40-gl shadow-reset">
                        <ul class="breadcome-menu">
                            <li><a href="{{url('omed/dashbard')}}">Dashboard</a> <span class="bread-slash">/</span>
                            </li>
                            <li><a href="{{url('omed/'.$page)}}">{{ucwords($page)}}</a> <span class="bread-slash">/</span>
                            </li>
                            <li><a href="#">Create</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="basic-form-area mg-b-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="sparkline12-list shadow-reset mg-t-30">
                        <div class="sparkline12-hd">
                            <div class="main-sparkline12-hd">
                                <h1>{{ucwords($page)}}</h1>
                                <div class="sparkline12-outline-icon">
                                    <span class="sparkline12-collapse-link"><i class="fa fa-chevron-up"></i></span>
                                    <span><i class="fa fa-wrench"></i></span>
                                    <span class="sparkline12-collapse-close"><i class="fa fa-times"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="sparkline12-graph">
                            <div class="basic-login-form-ad">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="all-form-element-inner">
                                            @if(!isset($area))
                                                <form action="{{route('area.store')}}" method="post">

                                            @else
                                                        <form action="{{route('area.update',$area->id)}}" method="post">
                                                            @method('PATCH')
                                            @endif
                                                    @csrf

                                            <div class="form-group-inner">
                                                <div class="row">
                                                    <div class="col-lg-3">
                                                        <label class="login2 pull-right pull-right-pro">State</label>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <select class="select2_demo_2 form-control state-select "   name="state" required style="width:100%;" >
                                                            <option selected disabled>State</option>
                                                            @foreach($states as $s)
                                                                <option value="{{$s->name}}" @if(isset($area) && $s->name == $area->state) {{'selected'}} @endif>{{ucwords($s->name)}}</option>
                                                            @endforeach
                                                        </select>
                                                    </div>

                                                </div>
                                            </div>

                                            <div class="form-group-inner">
                                                <div class="row">
                                                    <div class="col-lg-3">
                                                        <label class="login2 pull-right pull-right-pro">City</label>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <select class="select2_demo_2 form-control city-select "   name="city" required style="width:100%;"  >
                                                            @if(isset($city))
                                                            @foreach($city as $s)
                                                                <option value="{{$s->name}}" @if(isset($area) && $s->name == $area->city) {{'selected'}} @endif>{{ucwords($s->name)}}</option>
                                                            @endforeach
                                                            @else
                                                            <option selected disabled>City</option>
                                                                @endif

                                                        </select>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group-inner">
                                                <div class="row">
                                                    <div class="col-lg-3">
                                                        <label class="login2 pull-right pull-right-pro">Area</label>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <input type="text" class="form-control" name="area" value="@if(isset($area)){{$area->area}}@endif" placeholder="Enter Area Name" required>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group-inner">
                                                <div class="row">
                                                    <div class="col-lg-3">
                                                        <label class="login2 pull-right pull-right-pro">Pincode</label>
                                                    </div>
                                                    <div class="col-lg-4">
                                                        <input type="text" class="form-control" name="pincode" value="@if(isset($area)){{$area->pincode}}@endif" placeholder="Enter Pincode" required>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group-inner">
                                                <div class="login-btn-inner">
                                                    <div class="row">
                                                        <div class="col-lg-3"></div>
                                                        <div class="col-lg-6">
                                                            <div class="login-horizental cancel-wp pull-left">
                                                                <button class="btn btn-white" type="button" onclick="window.history.back();">Cancel</button>
                                                                <button class="btn btn-sm btn-primary login-submit-cs" type="submit">Save
                                                                </button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                                </form>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('additional_script')
    <script>
        $('.state-select').change(function() {
            $.ajax({
                type:"GET",
                url:"{{url('ajax/state')}}?state="+$(this).val(),
                success: function(response) {
                    if (response.success) {
                        $('.city-select').find('option').remove().end().append('<option selected hidden disabled>City</option>');
                        var city = response.city;
                        $.each(city, function(i, d) {
                            $('.city-select').append('<option>' + d.name + '</option>');
                        });
                    }
                },
            });
        });

        {{--// City Change--}}
        {{--$('.city-select').change(function() {--}}
            {{--$.ajax({--}}
                {{--type:"GET",--}}
                {{--url:"{{url('ajax/city')}}?city="+$(this).val()+'&state='+$('.state-select').val(),--}}
                {{--success: function(response) {--}}
                    {{--if (response.success) {--}}
                        {{--$('.area-select').find('option').remove().end().append('<option selected hidden disabled>Area</option>');--}}
                        {{--var area = response.area;--}}
                        {{--$.each(area, function(i, d) {--}}
                            {{--$('.area-select').append('<option>' + d.area + '</option>');--}}
                        {{--});--}}
                    {{--}--}}
                {{--},--}}
            {{--});--}}
        {{--});--}}
    </script>
@endsection